<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="sjxd7STAprdn134" failures="1" tests="1" name="testscripts.DataPrivacyIncident" time="79.756" errors="0" timestamp="2022-01-28T12:30:03 GMT+05:30" skipped="0">
  <testcase classname="testscripts.DataPrivacyIncident" name="TC056_Functionality_MainPage_IncidentDetails_Substate_PendingProblem" time="79.756">
    <failure message="Error -Create New Security Incident Filter Navigation button is not displayed in the Filter Navigation List; Error -Create New Security Incident Filter Navigation button is not displayed in the Filter Navigation List" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Error -Create New Security Incident Filter Navigation button is not displayed in the Filter Navigation List; Error -Create New Security Incident Filter Navigation button is not displayed in the Filter Navigation List
at org.testng.Assert.fail(Assert.java:99)
at com.cognizant.craft.CRAFTTestCase.tearDownTestRunner(CRAFTTestCase.java:120)
at testscripts.DataPrivacyIncident.TC056_Functionality_MainPage_IncidentDetails_Substate_PendingProblem(DataPrivacyIncident.java:25)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- TC056_Functionality_MainPage_IncidentDetails_Substate_PendingProblem -->
  <system-out/>
</testsuite> <!-- testscripts.DataPrivacyIncident -->
